services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password

  backend:
    build: ../backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ../data:/app/data  # Монтируем папку data
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: your-secret-key-here
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password

  frontend:
    build: ../frontend
    volumes:
      - frontend_build:/app/build

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - frontend_build:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_build: